---

- hosts: all
  become: true
  pre_tasks:
    - name: update cache (Void)
      xbps:
        update_cache: yes
      when: ansible_distribution == "Void"

- hosts: all
  become: true
  tasks:

    - name: Install package
      package:
        name:
          - zramen
          - htop
          - vim
          - docker
          - python3-pip
          - gcc
          - libffi-devel
          - python3-devel
          - cronie

    - name: Create swap file
      shell: |
        [ $(swapon | grep swapfile) != "" ] || swapoff /swapfile
        rm -f /swapfile
        fallocate -l 8G /swapfile
        chmod 600 /swapfile
        mkswap /swapfile
        swapon /swapfile

    - name: add swap to fstab
      lineinfile:
        path: /etc/fstab
        line: "/swapfile swap swap defaults 0 0"

    - name: copy cron service in /var/service (Void)
      file:
        src: /etc/sv/cronie
        dest: /var/service
        state: link
      when: ansible_distribution == "Void"

    - name: start cron service
      service:
        name: cronie
        state: started

    - name: copy zramen service in /var/service (Void)
      file:
        src: /etc/sv/zramen
        dest: /var/service
        state: link
      when: ansible_distribution == "Void"

    - name: start zramen service
      service:
        name: zramen
        state: started
      when: ansible_distribution == "Void"

    - name: install python library for docker-compose
      pip:
        name:
          - python-docker
          - docker-compose

    - name: copy docker service in /var/service (Void)
      file:
        src: /etc/sv/docker
        dest: /var/service
        state: link
      when: ansible_distribution == "Void"

    - name: start docker service
      service:
        name: docker
        state: started

    - name: copy docker-compose.yml files
      tags:
        - docker
      copy:
        src: docker_compose
        dest: /opt/docker
        owner: root
        group: root
        mode: 0644

    - name: Start docker-compose.yml files
      tags:
        - docker
      docker_compose:
        project_src: /opt/docker/docker_compose
        recreate: always
        files:
          - watchtower.yml
          - dashy.yml
          - glances.yml
          - pihole.yml
          # - minidlna.yml
          # - booksonic.yml
          # - duckdns.yml
          # - homeassistant.yml
          # - jackett.yml
          # - jellyfin.yml
          # - nextcloud.yml
          # - sonar.yml
          # - transmission.yml

    - name: "Cleanup docker"
      cron:
        name: "cleanup docker"
        hour: "23"
        job: "docker system prune --all -f && docker volume prune --force"

    - name: "Update the system"
      cron:
        name: "update the system"
        hour: "23"
        job: "xbps-install -Syyu"

