---

- hosts: all
  become: true
  pre_tasks:
    - name: update cache (Void)
      xbps:
        update_cache: yes
      when: ansible_distribution == "Void"

- hosts: all
  become: true
  tasks:

    - name: install package
      package:
        name:
          - zramen
          - htop
          - vim
          - docker
          - python3-pip
          - gcc
          - libffi-devel
          - python3-devel

    - name: copy zramen service in /var/service (Void)
      file:
        src: /etc/sv/zramen
        dest: /var/service
        state: link
      when: ansible_distribution == "Void"

    - name: start zramen service
      service:
        name: zramen
        state: started
      when: ansible_distribution == "Void"

    - name: install python library for docker-compose
      pip:
        name:
          - python-docker
          - docker-compose

    - name: copy docker service in /var/service (Void)
      file:
        src: /etc/sv/docker
        dest: /var/service
        state: link
      when: ansible_distribution == "Void"

    - name: start docker service
      service:
        name: docker
        state: started

    - name: copy docker-compose.yml files
      copy:
        src: docker_compose
        dest: /opt/docker
        owner: root
        group: root
        mode: 0644

    - name: start docker-compose.yml files
      docker_compose:
        project_src: /opt/docker/docker_compose
        recreate: always
        files:
          - booksonic.yml
          - duckdns.yml
          - flame.yml
          - homeassistant.yml
          - homer.yml
          - jackett.yml
          - jellyfin.yml
          - nextcloud.yml
          - pihole.yml
          - sonar.yml
          - transmission.yml
          - watchtower.yml
          - glances.yml
          - minidlna.yml

