version: '3.7'
services:
  glances:
    build:
      context: ./glances
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - "61208:61208"
      # - "61209:61209"
    network_mode: host
    environment:
      # - GLANCES_OPT="-w"
      GLANCES_OPT: "-w"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    pid: "host"
