version: '3.7'
services:
  glances:
    build:
      context: ./glances
      dockerfile: Dockerfile
    restart: always
    ports:
      - "61208:61208"
    environment:
      GLANCES_OPT: "-w"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    pid: "host"
