---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    # volumes:
    #   - /path/to/library:/config
    #   - /path/to/tvseries:/data/tvshows
    #   - /path/to/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
